name: Build and Upload to GCS

on:
  pull_request:
    types:
      - closed
    branches:
      - 'feature/github_actions_gcs_rom_upload'

jobs:
  build-and-upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Build with Gradle
      run: ./gradlew build

    - name: gcloud auth
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: '${{ secrets.GCP_PROJECT_ID }}'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'app/build/outputs/apk/debug/app-debug.apk'
        destination: 'hs-svm-workgroup002.appspot.com/DevOps/ROM'
    
