name: Android CI

# 実行の条件
on:
  push:
    # masterへマージする時
    branches: [ "master" ]
  pull_request:
    # masterへのPRを作成した時
    branches: [ "master" ]

jobs:
  # Android Lintを使って静的解析する
  lint:
    runs-on: ubuntu-latest
    steps:
    # チェックアウト
    - uses: actions/checkout@v4
    # 静的解析
    - name: Run Inspection
      run: ./gradlew lint
    # 結果の表示
    - uses: yutailang0119/action-android-lint@v1
      with:
        xml_path: '*'
